GET http://localhost:8000

###
POST http://localhost:8000/messages/new HTTP/1.1
content-type: application/json

{
	"message": "kk bye",
	"name": "Other Julian",
	"timestamp": "11/3/20",
	"received": "true"
}

#### 
GET http://localhost:8000/messages/sync